language: cpp


matrix:
  include:
    - os: linux
      image: xenial
      compiler: clang

    - os: linux
      image: xenial
      compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install g++-8 libstdc++-8-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - tests/painless-tests
